openapi: 3.0.0
servers: 
  - url: https://hifx2vr6f4.execute-api.eu-west-1.amazonaws.com/dev
info:
  title: Shop-BE import-service
  description: Import chemicals service
  version: 1.0.0
paths:
  /import:
    get:
      operationId: importProductsFile
      summary: importProductsFile
      description: Get all chemicals
      parameters:
        - in: query
          name: name
          required: true
          schema:
            type: string
          description: Uploaded filename
      responses:
        '200':
          description: Signed URL
          content:
            application/json:
              schema:
                type: object
                properties:
                  signedURL:
                    type: string
                    description: Signed URL
        '500':
          description: Server side error occured
          content: {}
